### ISSUE TITLE
Question regarding upstream work (OpenVPN)

### ISSUE THREAD

**Issue by baimafeima** [azirevpn/azclient#13]
What patches do you use for OpenVPN and do you actively upstream them into OpenVPN so that others can benefit as well?

**Comment by tobiasa1** [comment]
We do not modify OpenVPN in any way, just shipping the latest binaries for Windows and MacOS within the azclient repository.

**Comment by baimafeima** [comment]
Thanks for the feedback. I am just trying to investigate in what sense having a customized OpenVPN client could present a new attack surface and introduce more vulnerabilities than just using OpenVPN itself.
