### ISSUE TITLE
Request clarification regarding nessla.se

### ISSUE THREAD

**Issue by baimafeima** [azirevpn/azclient#26]
When opening https://www.azirevpn.com/ my IP is also automatically sent to https://www.nessla.se
Could you please clarify what nessla.se is about and why you would not rather opt for the cleanest possible website without any additional IP directs other than to https://www.azirevpn.com/

**Comment by r1ppe** [comment]
This is not the place for AzireVPN Q/A.
Please send your question to our support or drop by #azirevpn on Freenode.
