### ISSUE TITLE
"Download now" does nothing

### ISSUE THREAD

**Issue by mattcoxonline** [azirevpn/azclient#4]
I guess this is a known issue / still under development... but when I click the "Download Now" button on the _Update Available_ dialog, the dialog window just disappears and nothing happens.

![screenshot from 2017-04-11 16-54-28](https://cloud.githubusercontent.com/assets/673542/24915568/cc0db816-1ed7-11e7-8e5e-035afd982192.png)

**Comment by r1ppe** [comment]
This issue was related to our backend which did not return a proper response, it has been resolved now.

Thanks for reporting!
