### ISSUE TITLE
Option to remember account password.

### ISSUE THREAD

**Issue by GHPLM** [azirevpn/azclient#7]
At present the client does not have an option to store the account password, meaning that two separate passwords (account+root) have to be typed on startup and every time the user wants to change server. Allowing the client to remember the account password would help (as would only requiring the root password at startup, rather than on every server change).

**Comment by CodeBrauer** [comment]
Good idea, on macOS the password can be stored in the system keychain - would be nice.

**Comment by michael1900** [comment]
When the option to save password will be implemented?

**Comment by baimafeima** [comment]
Just a short note, I have requested `azclient` to be added to the Solus* repositories so it can be easily installed with a one-click operation in the Software Center: https://dev.solus-project.com/T5468

I am not sure if it will be successful but in any case, just wanted to let you know and I hope that some of the open issues here on GitHub can be added to the next version soon. 

*Solus is my operating system of choice, I am not affiliated with their project: https://solus-project.com/

**Comment by tobiasa1** [comment]
This was fixed in commit 39846d277b4cdf4eaf88e2d3f56dd8b06c113356

**Comment by michael1900** [comment]
Hi, ho to log in with token? Is there a guide?
